/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
*/


import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int t = in.nextInt();
        for(int a0 = 0; a0 < t; a0++){
            long n = in.nextLong();
            findFib(n);
        }
    }
    
    public static void findFib(long n){
        long a = 1;
        long b = 2;
        long c = 0;
        long sum = 0;
        
        // did not use recursion as it might lead to too many recursive call problem.
        
        // check if value of n is greater than 2 as first even fibonacci is at position 2.
        if(n > 1){
            // iterate until current fibonacci number is less than or equal to value of n
            while( c <= n){
                // if its even then add it to the sum
                if(b % 2 == 0){
                    sum += b;
                }
                // compute next number
                c = a+b;
                a = b;
                b = c;
            }        
        }
        System.out.println(sum);
        
    }
}
